# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('business_name', models.CharField(max_length=80, verbose_name='Raz\xf3n Social')),
                ('rfc', models.CharField(max_length=17, verbose_name='RFC')),
                ('address', models.CharField(max_length=255, verbose_name='Direcci\xf3n')),
                ('zip_code', models.IntegerField(verbose_name='C\xf3digo Postal')),
                ('city', models.IntegerField(choices=[(1, b'CAMPECHE')], verbose_name='Ciudad')),
                ('town', models.IntegerField(choices=[(1, b'CALKIN\xc3\x8d'), (2, b'CAMPECHE'), (3, b'CARMEN'), (4, b'CHAMPOT\xc3\x93N'), (5, b'HECELCHAK\xc3\x81N'), (6, b'HOPELCH\xc3\x89N'), (7, b'PALIZADA'), (8, b'TENABA'), (9, b'ESC\xc3\x81RCEGA'), (10, b'CALAKMUL'), (11, b'CANDELARIA')], verbose_name='Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('price_type', models.IntegerField(choices=[(1, b'REGULAR'), (2, b'PRONTO PAGO')], verbose_name='Tipo precio')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10, verbose_name='Serie')),
                ('consecutive', models.IntegerField(verbose_name='Consecutivo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
        ),
    ]
