# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('curp', models.CharField(max_length=17, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=17, verbose_name='RFC')),
                ('address', models.CharField(max_length=150, verbose_name='Direcci\xf3n')),
                ('zip_code', models.IntegerField(verbose_name='C\xf3digo Postal')),
                ('city', models.IntegerField(choices=[(1, 'CAMPECHE')], verbose_name='Ciudad')),
                ('town', models.IntegerField(choices=[(1, 'CALKIN\xcd'), (2, 'CAMPECHE'), (3, 'CARMEN'), (4, 'CHAMPOT\xd3N'), (5, 'HECELCHAK\xc1N'), (6, 'HOPELCH\xc9N'), (7, 'PALIZADA'), (8, 'TENABA'), (9, 'ESC\xc1RCEGA'), (10, 'CALAKMUL'), (11, 'CANDELARIA')], verbose_name='Municipio')),
                ('active', models.BooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Creado por')),
            ],
        ),
    ]
