# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Importe de pago')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('debt_month', models.IntegerField(verbose_name='Mes que se adeuda')),
                ('debt_year', models.IntegerField(verbose_name='A\xf1o de la deuda')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='D\xeda que se paga la deuda')),
                ('deleted', models.BooleanField(default=False, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.IntegerField(verbose_name='Consecutivo de folio')),
                ('folio', models.CharField(max_length=50, verbose_name='Folio del pago')),
                ('paid_month', models.IntegerField(verbose_name='Mes del pago')),
                ('paid_year', models.IntegerField(verbose_name='A\xf1o del pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Importe de pago')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('partial', models.BooleanField(default=False, verbose_name='Pago parcial')),
                ('canceled', models.BooleanField(default=False, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='paid',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_client', to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='debt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_client', to='clients.Client', verbose_name='Cliente'),
        ),
    ]
