# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160423_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='town',
            field=models.IntegerField(choices=[(1, b'CALKIN\xc3\x8d'), (2, b'CAMPECHE'), (3, b'CARMEN'), (4, b'CHAMPOT\xc3\x93N'), (5, b'HECELCHAK\xc3\x81N'), (6, b'HOPELCH\xc3\x89N'), (7, b'PALIZADA'), (8, b'TENABA'), (9, b'ESC\xc3\x81RCEGA'), (10, b'CALAKMUL'), (11, b'CANDELARIA')], verbose_name='Municipio'),
        ),
    ]
